version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: salary-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ./salary-api
      dockerfile: Dockerfile
    container_name: salary-api
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ./salary-api:/app
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      RAILS_ENV: development
    depends_on:
      - db

  web:
    build:
      context: ./salary-web
      dockerfile: Dockerfile
    container_name: salary-web
    command: npm run dev -- --host
    volumes:
      - ./salary-web:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - api

volumes:
  pgdata:
